- name: default values
  hosts: localhost
  tasks:
  - name: print default values
    ansible.builtin.debug:
     msg: "hello {{class | default('ansible') }}"

- name: upper case
  hosts: localhost
  vars:
    greeting: "hello, good morning"
  tasks:
  - name: convert into upper case
    ansible.builtin.debug:
      msg: "{{ greeting | upper }}"

- name: lower case
  hosts: localhost
  vars:
    greeting: "HELLO, GOOD MORNING"
  tasks:
  - name: convert into lower case
    ansible.builtin.debug:
      msg: "{{ greeting | lower }}"

- name: remove duplicates
  hosts: localhost
  numbers: [1,1,2,3,4,4,5,]
  tasks:
  - name: remove duplicates
    ansible.builtin.debug:
     msg: "{{ numbers | unique }}"
